server:
  port: 8080
  servlet:
    context-path: /


spring:
  # todo 개발 데이터베이스 연결 ( h2가 편하면 h2로 바꾸자 )
  datasource:
    url: jdbc:mariadb://localhost:3306/tutorial?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    hikari:

  jpa:
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
    generate-ddl: true
    show-sql: true # 콘솔창에 sql 출력
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql문 이쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화 ( jpa 성능 개선을 위함 )


  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한
logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

# 3-handShake
feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 5초 이내로 연결을 못하면 끊김
        readTimeout: 5000 # 연결 된 상태에서 5초 이내로 응답이 없으면 끊기게 설정

